"""initial schema

Revision ID: 99213af6b67f
Revises: 
Create Date: 2026-07-31 20:01:32.107795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99213af6b67f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=16), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_status'), ['status'], unique=False)

    op.create_table('notification_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('agent_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id')
    )
    with op.batch_alter_table('agent_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_credentials_revoked_at'), ['revoked_at'], unique=False)

    op.create_table('agent_nonces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_nonces_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nonces_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nonces_nonce'), ['nonce'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)

    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)

    op.create_table('baseline_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('check_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_results', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_results_batch', ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baseline_results_check_id'), ['check_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baseline_results_host_id'), ['host_id'], unique=False)

    op.create_table('detection_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_host_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_token_validity', ['expires_at', 'used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('file_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_changes_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_changes_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_changes_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('inventory_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=16), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('boot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_batch_host', ['batch_id', 'host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_host_id'), ['host_id'], unique=False)

    op.create_table('listening_port_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('local_address', sa.String(length=64), nullable=False),
    sa.Column('local_port', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listening_port_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listening_port_snapshots_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_port_snapshots_batch', ['batch_id'], unique=False)

    op.create_table('metric_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('network_bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('network_bytes_recv', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.create_index('ix_metric_samples_batch_host', ['batch_id', 'host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_samples_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_samples_host_id'), ['host_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_severity'), ['severity'], unique=False)

    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_web_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_web_sessions_validity', ['expires_at', 'revoked_at'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('host_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('process_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_id', sa.String(length=36), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('executable', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_process_snapshots_batch', ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_snapshots_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_snapshots_inventory_id'), ['inventory_id'], unique=False)

    op.create_table('report_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_jobs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_jobs_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_jobs_status'), ['status'], unique=False)

    op.create_table('alert_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_transitions_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_transitions_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_transitions_created_at'), ['created_at'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_channel_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_alert_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('alert_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_transitions_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_transitions_alert_id'))
        batch_op.drop_index(batch_op.f('ix_alert_transitions_actor_user_id'))

    op.drop_table('alert_transitions')
    with op.batch_alter_table('report_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_report_jobs_report_type'))
        batch_op.drop_index(batch_op.f('ix_report_jobs_job_id'))

    op.drop_table('report_jobs')
    with op.batch_alter_table('process_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_snapshots_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_process_snapshots_host_id'))
        batch_op.drop_index('ix_process_snapshots_batch')

    op.drop_table('process_snapshots')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_host_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_first_seen_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_web_sessions_validity')
        batch_op.drop_index(batch_op.f('ix_web_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_web_sessions_expires_at'))

    op.drop_table('web_sessions')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_severity'))
        batch_op.drop_index(batch_op.f('ix_security_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_security_events_host_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_batch_id'))

    op.drop_table('security_events')
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_samples_host_id'))
        batch_op.drop_index(batch_op.f('ix_metric_samples_collected_at'))
        batch_op.drop_index('ix_metric_samples_batch_host')

    op.drop_table('metric_samples')
    with op.batch_alter_table('listening_port_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_port_snapshots_batch')
        batch_op.drop_index(batch_op.f('ix_listening_port_snapshots_host_id'))

    op.drop_table('listening_port_snapshots')
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_host_id'))
        batch_op.drop_index('ix_inventory_batch_host')

    op.drop_table('inventory_snapshots')
    with op.batch_alter_table('file_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_changes_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_file_changes_host_id'))
        batch_op.drop_index(batch_op.f('ix_file_changes_batch_id'))

    op.drop_table('file_changes')
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_created_by_user_id'))
        batch_op.drop_index('ix_enrollment_token_validity')

    op.drop_table('enrollment_tokens')
    op.drop_table('detection_rules')
    with op.batch_alter_table('baseline_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_results_host_id'))
        batch_op.drop_index(batch_op.f('ix_baseline_results_check_id'))
        batch_op.drop_index('ix_baseline_results_batch')

    op.drop_table('baseline_results')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_created_by_user_id'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_nonces_nonce'))
        batch_op.drop_index(batch_op.f('ix_agent_nonces_expires_at'))
        batch_op.drop_index(batch_op.f('ix_agent_nonces_agent_id'))

    op.drop_table('agent_nonces')
    with op.batch_alter_table('agent_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_credentials_revoked_at'))

    op.drop_table('agent_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('notification_channels')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_status'))
        batch_op.drop_index(batch_op.f('ix_hosts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_hosts_hostname'))

    op.drop_table('hosts')
    # ### end Alembic commands ###
